version: '3'
services:
    mysql:
        image: mocitec-mysql
        build: ./build/mysql
        restart: always
        environment:
            - MYSQL_DATABASE=db_mocitec
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        ports:
            - '127.0.0.1:3306:3306'
        volumes:
            - mysql:/var/lib/mysql
    apache:
        image: mocitec-apache
        build: ./build/apache
        restart: always
        ports:
            - '80:80'
        volumes:
            - ./app:/var/www/html
            - vendor:/var/www/html/vendor
volumes:
    mysql:
    vendor: